name = "TestPkgLH"
uuid = "00a7633a-72ae-5472-a4e7-9084f2f3a33b"
authors = ["hendri54 <hendricksl@protonmail.com>"]
version = "0.1.0"

[deps]
ConfigLH = "17a1d2b7-f0f8-5fc2-a491-2d61ab6c0a52"

[compat]
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
